# https://github.com/lowlighter/metrics

name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
			- name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Onexyq
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          # 此插件为文档中的 🧮 Repositories traffic
          plugin_traffic: yes
          # 此插件为文档中的 👨‍💻 Lines of code changed
          plugin_lines: yes
          # 此插件为文档中的 🙋 Introduction
          plugin_introduction: yes
          # 此插件为文档中的 🎫 Gists
          plugin_gists: yes
          # 此插件为文档中的 💫 Star lists
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_only: Awesome
					
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
